server:
  port: 9250

swagger:
  enable: true
#  application-name: ${spring.application.name}
#  application-version: 1.0
#  application-description: 门禁后台接口
#  try-host: http://localhost:${server.port}

mybatis-plus:
  type-aliases-package: com.wim.aero.acs.db.**.entity
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      table-underline: true
      logic-not-delete-value: 0
      logic-delete-value: 1

spring:
  profiles:
    active: "@profiles.active@"
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:sqlserver://113.57.214.58:14339;databaseName=ykt
    username: sa
    password: iafc@2022
  activemq:
    in-memory: true
    broker-url: tcp://192.168.2.236:61616
    user: admin
    password: zhdt@2022
    pool:
      enabled: true
      max-connections: 10
      idle-timeout: 30000
    #队列名称
    queueName:
      # 访问事件队列
      accessQueue: accessQueue
      # 告警事件队列
      alarmQueue: alarmQueue
      #日志事件队列
      logQueue: logQueue



httppool:
  maxTotal: 200
  defaultMaxPerRoute: 100
  connectTimeout: 3000
  connectionRequestTimeout: 3000
  socketTimeout: 3000
  validateAfterInactivity: 2000

comm-service-info:
  url: https://192.168.2.72:7087

dst:
  list:
    - start: "2022/03/13 02:00:00"
      end: "2022/11/06 01:00:00"
    - start: "2023/03/12 02:00:00"
      end: "2023/11/05 01:00:00"
    - start: "2024/03/10 02:00:00"
      end: "2024/11/03 01:00:00"
    - start: "2025/03/09 02:00:00"
      end: "2025/11/02 01:00:00"
    - start: "2026/03/08 02:00:00"
      end: "2026/11/01 01:00:00"
    - start: "2027/03/14 02:00:00"
      end: "2027/11/07 01:00:00"
    - start: "2028/03/12 02:00:00"
      end: "2028/11/05 01:00:00"
    - start: "2029/03/11 02:00:00"
      end: "2029/11/04 01:00:00"
    - start: "2030/03/10 02:00:00"
      end: "2030/11/03 01:00:00"
    - start: "2031/03/09 02:00:00"
      end: "2031/11/02 01:00:00"
    - start: "2032/03/14 02:00:00"
      end: "2032/11/07 01:00:00"
    - start: "2033/03/13 02:00:00"
      end: "2033/11/06 01:00:00"
    - start: "2034/03/12 02:00:00"
      end: "2034/11/05 01:00:00"
    - start: "2035/03/11 02:00:00"
      end: "2035/11/04 01:00:00"
